# Generated by Django 5.2.7 on 2025-11-01 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_coupon_order_discount_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_amount',
            new_name='discount',
        ),
    ]
